#############################################################################################
#
# Two domains, four sub-domains.
#
#############################################################################################
---
  aliases:
    - &rs0 http://198.101.205.153
    - &rs1 http://198.101.205.155
    - &rs2 http://198.101.205.156
    - &rs3 http://198.101.203.202
    - &rs4 http://198.101.209.178
    - &rs5 http://198.101.209.247
    - &rs6 http://198.101.202.188
    - &rs7 http://198.101.207.34
    - &rs8 http://198.101.207.48
    - &rs9 http://198.101.207.236
    - &ip-10-4-178-42 http://ec2-67-202-45-247.compute-1.amazonaws.com
    - &ip-10-196-115-185 http://ec2-23-20-43-173.compute-1.amazonaws.com
    - &ip-10-99-65-6 http://ec2-50-17-85-234.compute-1.amazonaws.com
    - &ip-10-212-135-203 http://ec2-23-22-68-94.compute-1.amazonaws.com
    - &ip-10-195-205-62 http://ec2-50-17-57-243.compute-1.amazonaws.com
    - &ip-10-212-123-155 http://ec2-50-16-141-176.compute-1.amazonaws.com
    - &ip-10-114-61-53 http://ec2-184-73-138-154.compute-1.amazonaws.com
    - &ip-10-196-39-9 http://ec2-107-20-47-98.compute-1.amazonaws.com
    - &ip-10-203-83-56 http://ec2-184-73-2-121.compute-1.amazonaws.com
    - &ip-10-117-35-119 http://ec2-23-22-144-216.compute-1.amazonaws.com

#############################################################################################
#
# The Context server used by all nodes and routers as needed.
#
#############################################################################################
  rs0:
    name: *rs0
    role: context_manager

#############################################################################################
#
# Routers; we the bridge router is in Rackspace.  Both Amazon and Rackspace then have
# two cell routers each.
#
# This uses five images, one for the primary router and four for each of the four cells.
#
# Primary router, only routes to other routers in ths configuration.
#
#############################################################################################
  rs1:
    name: *rs1
    context_server: *rs0
    role: router
    children:
      - *rs2
      - *rs3
      - *ip-10-4-178-42
      - *ip-10-196-115-185

  rs2:
    name: *rs2
    context_server: *rs0
    role: router
    parent: *rs1
    children:
      - *rs4
      - *rs5
      - *rs6

  rs3:
    name: *rs3
    context_server: *rs0
    role: router
    parent: *rs1
    children:
      - *rs7
      - *rs8
      - *rs9

  ip-10-4-178-42:
    name: *ip-10-4-178-42
    context_server: *rs0
    role: router
    parent: *rs1
    children:
      - *ip-10-99-65-6
      - *ip-10-212-135-203
      - *ip-10-195-205-62
      - *ip-10-212-123-155

  ip-10-196-115-185:
    name: *ip-10-196-115-185
    context_server: *rs0
    role: router
    parent: *rs1
    children:
      - *ip-10-114-61-53
      - *ip-10-196-39-9
      - *ip-10-203-83-56
      - *ip-10-117-35-119

#############################################################################################
#
# These are the nodes available to the network.
#
#############################################################################################

  rs4:
    name: *rs4
    role: node
    context_server: *rs0
    repository: repo_new_location.dat
    parent: *rs2

  rs5:
    name: *rs5
    role: node
    context_server: *rs0
    parent: *rs2

  rs6:
    name: *rs6
    role: node
    context_server: *rs0
    repository: repo_old_location.dat
    parent: *rs2

  rs7:
    name: *rs7
    role: node
    context_server: *rs0
    repository: repo_secret.dat
    parent: *rs3

  rs8:
    name: *rs8
    role: node
    context_server: *rs0
    repository: repo_topsecret.dat
    parent: *rs3

  rs9:
    name: *rs9
    role: node
    context_server: *rs0
    parent: *rs3


  ip-10-99-65-6:
    name: *ip-10-99-65-6
    role: node
    context_server: *rs0
    parent: *ip-10-4-178-42

  ip-10-212-135-203:
    name: *ip-10-212-135-203
    role: node
    context_server: *rs0
    parent: *ip-10-4-178-42

  ip-10-195-205-62:
    name: *ip-10-195-205-62
    role: node
    repository: repo_index.dat
    context_server: *rs0
    parent: *ip-10-4-178-42

  ip-10-212-123-155:
    name: *ip-10-212-123-155
    role: node
    context_server: *rs0
    parent: *ip-10-4-178-42

  ip-10-114-61-53:
    name: *ip-10-114-61-53
    role: node
    context_server: *rs0
    parent: *ip-10-196-115-185

  ip-10-196-39-9:
    name: *ip-10-196-39-9
    role: node
    context_server: *rs0
    parent: *ip-10-196-115-185

  ip-10-203-83-56:
    name: *ip-10-203-83-56
    role: node
    context_server: *rs0
    parent: *ip-10-196-115-185

  ip-10-117-35-119:
    name: *ip-10-117-35-119
    role: node
    context_server: *rs0
    parent: *ip-10-196-115-185
